[package]
name = "hex_to_base64"
version = "0.1.0"
authors = ["betameta123 <kylehuang10@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
